### ISSUE TITLE
Add ability to sign hash of a file instead of requiring a file itself

### ISSUE THREAD

**Issue by vlsi** [sigstore/sigstore-java#118]
**Description**

The current API requires to have a file: `dev.sigstore.KeylessSigner#sign(Path artifact)`, however, in fact it does not need the file itself, and it should be enough to pass a checksum.

It would probably make it easier to separate the build and signing steps: the build step would produce a list of checksums, and the signer could sign them. There won't be a need to pass the full artifact contents.

**Comment by loosebazooka** [comment]
fixed with #172 and released in 0.2.0
