### ISSUE TITLE
Unable to build project in IDEA after Gradle plugin in Kotlin added

### ISSUE THREAD

**Issue by szpak** [sigstore/sigstore-java#173]
### Description

I was not able to build the project in IDEA 2022.1.4 (nor in 2021.3.3). The build from Gradle passes (with excluded tests passes).

### Steps to reproduce

1. Perform fresh project import into IDEA.
2. Rebuild project (CTRL-F9 or Build → Rebuild Project)

### Actual behavior

```
/home/.../sigstore-java/sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev.sigstore.sign-base.gradle.kts
Kotlin: No script runtime was found in the classpath: class 'kotlin.script.templates.standard.ScriptTemplateWithArgs' not found. Please add kotlin-script-runtime.jar to the module dependencies.
```
and after adding `implementation(kotlin("script-runtime"))` in the corresponding module (as suggested in [KTIJ-601](https://youtrack.jetbrains.com/issue/KTIJ-601)):

```
/home/.../sigstore-java/sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev.sigstore.sign-base.gradle.kts:20:24
Kotlin: Unresolved reference: Named
```
followed by the other classes in that file.

### Expected behavior

Everything builds successfully. Tests are green. I can start hacking on the project :-).

### Additional information

I spent some time to try different things, including:
1. Adding `implementation(gradleApi())` in the module - the same errors.
2. Bumping the Kotlin version used in the project to 1.6.21 (as in the used Gradle version) - no more warnings in the Gradle, but the same errors in Idea.
3. Downgrade Idea to 2021.3.3 to be able to use compatible Kotlin plugin with Kotlin 1.6.21 - the same errors.
4. Adding the explicit imports - `Kotlin: Not enough information to infer type variable T`.

I had some issues with different Groovy versions in the Gradle project, but Kotlin and `.kts` seems to be way more problematic :-/.

### Version

Version from master (as of https://github.com/sigstore/sigstore-java/commit/db10e80a9b2831f13b2efc85aa4eba7a9410aeaf)

**Comment by vlsi** [comment]
`src/main/kotlin/dev.sigstore.sign-base.gradle.kts:20:24` means that IDEA's builder does not support [Gradle precompiled script plugins](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins).

Note: even if `dev.sigstore.sign-base.gradle.kts` is removed, IDEA's builder still fails to compile code in `build-logic`.
I would recommend using "Build and run using" Gradle which is the default in IDEA (see https://www.jetbrains.com/help/idea/gradle.html#gradle_settings_access)

**Comment by vlsi** [comment]
Frankly speaking, I have never tried using IDEA builder for Gradle precompiled scripts. I did a quick search, and I did not find such a request.

**Comment by szpak** [comment]
When switched to the Gradle builder, it built successfully, thanks.

Having some small sample with precompiled script plugin, I will report it to Jetbrains. Closing for now.
