### ISSUE TITLE
Release sigstore-java 0.3.0

### ISSUE THREAD

**Issue by loosebazooka** [sigstore/sigstore-java#332]
- [x] tag and build 0.3.0 
    - https://github.com/sigstore/sigstore-java/actions/runs/4107271348
    - https://github.com/sigstore/sigstore-java/releases/tag/v0.3.0
- [x] release to maven central

FYI @patflynn @vlsi, tagging off of main@ 4ffe2674e1e9e268c00a4f4afa5264fdd399d453

**Comment by loosebazooka** [comment]
This is a less than ideal publishing system, but ok to release (@patflynn, @vlsi)?

**Comment by vlsi** [comment]
The more releases the better
