### ISSUE TITLE
Sigstore-Java verifying artifacts signed by Github Workflows

### ISSUE THREAD

**Issue by Miranlfk** [sigstore/sigstore-java#468]
**Question**
Hi folks! Ive mention the question in the [#java](https://sigstore.slack.com/archives/C03239XUL92) channel but incase its missed. Small question - I'm signing some release artifacts keylessly via Github action. The artifacts are being used in a java client after. Can i do the verification within the Java client using Sigstore-Java implementation. If this is possible can anyone assisst me with this. Thanks and Cheers!

**Comment by vlsi** [comment]
See https://github.com/sigstore/sigstore-java/blob/8f4794c6cfc8571d16243f393e343a25cccd7470/sigstore-cli/src/main/java/dev/sigstore/cli/Verify.java#L40

However, sigstore-java does not handle certificate rotations yet (see https://github.com/sigstore/sigstore-java/issues/60), so every certificate rotation requires releasing a new sigstore-java version currently.
