### ISSUE TITLE
`The target server failed to respond` when releasing with Sigstore

### ISSUE THREAD

**Issue by sgammon** [sigstore/sigstore-java#489]
**Description**

We are using Gradle, and the Sigstore Gradle Plugin, to release a rather large open source library; I say "rather large" because there are ~30 project modules, some of which are Kotlin Multiplatform targets which _themselves_ have several publications. This results in a lot of activity against Sigstore when we're releasing; probably on the order of hundreds of requests, maybe low thousands, over the span of about 10 minutes.

It is very rare that these requests fully complete. The build regularly halts with the following error:
```
* What went wrong:
Execution failed for task ':packages:proto:proto-protobuf:sigstoreSignMavenPublication'.
> There was a failure while executing work items
   > A failure occurred while executing dev.sigstore.sign.work.SignWorkAction
      > The target server failed to respond
```

Where it halts is sort of random, but it's always further along in the build. Because Sigstore signing happens for each module before it is published (but not before all publishing), this often results in a build which cannot be released to Maven Central because it is incomplete in some way (Sigstore failed, an artifact wasn't uploaded, so structural integrity is broken in stage).

We probably can't adopt Sigstore until there are at least some retries on this signing mechanism. While we've tried, it is not currently possible to meet Maven Central's pre-release rules while also signing via Sigstore, at least for a release cycle as large as ours.

To make matters worse, we know that re-running this release _sometimes_ gets it to pass, which must mean that a lot of traffic is sent to Sigstore unnecessarily, in order to complete a publish cycle which halted part way (but still persisted signatures).

It seems like retries would solve the issue, because the failures are transient and unrelated to any specific module. A longer timeout might also quickly fix it, at least for us, as it seems to timeout around 10 seconds, and some of these libraries include native code which pushes them into the ~50MB+ range.

**Version**

Latest

**Comment by loosebazooka** [comment]
Thanks. I think retries are probably required before we do any ga release. @vlsi who has been developing the gradle plugin might have more information about concurrency here. Perhaps we are just going too hard against the server and are hitting rate limiting?

**Comment by loosebazooka** [comment]
Actually do you know what error code you were hitting and what time? was it a 500? or just a timeout on the connection?

**Comment by loosebazooka** [comment]
I think the solution here is to add retries on 5xx for rekor but @sgammon I don't know if this covers your usecase?

**Comment by sgammon** [comment]
@loosebazooka Sorry, missed first comment, thank you for the tag (that makes it show up in Mentions).

These were timeouts, not 500s

**Comment by sgammon** [comment]
It always seemed to time out on larger payloads, but maybe I'm just imagining that. Also, it seemed to timeout later in the build, so rate limiting/throttling might be involved?

**Comment by loosebazooka** [comment]
@bobcallaway mentioned a database issue with timeouts that may have been the root cause of this. Fixed 2 weeks ago?

We should still retry on 429 (rate limiting) and 5xx (server error).

**Comment by sgammon** [comment]
@loosebazooka just wanted to confirm that we are seeing fewer issues now, thank you

**Comment by loosebazooka** [comment]
But still seeing them?

**Comment by sgammon** [comment]
@loosebazooka yes, but only on a retried deploy, so at this point it really may be rate limiting. We only see it after ~tens or ~hundreds of requests.

**Comment by loosebazooka** [comment]
Kk. Well let us know if there are any actionable failures and we can tweak the client some more
