### ISSUE TITLE
Update to protobuf-spec 0.2.1

### ISSUE THREAD

**Issue by loosebazooka** [sigstore/sigstore-java#528]
-[ ] InclusionPromise (SET) is now optional if an rfc 3161 TSA issued timestamp is available
-[ ] If the certificate is currently valid, then SET and Rfc 3161 are not required to be present at verification time
-[ ] An inclusion proof in a trusted log MUST be present and verified

fyi: @haydentherapper this match up?

**Comment by haydentherapper** [comment]
Correct! One thing to consider is if you want to handle v0.1 bundles where the inclusion proof was not valid. I think no, require v0.2+

**Comment by loosebazooka** [comment]
We have some bundles in public (maybe just sigstore projects on maven central). But I really think we don't care until GA.

**Comment by loosebazooka** [comment]
fixed by #544
