### ISSUE TITLE
Pinned Fulcio and Rekor root certs should be updatable via TUF

### ISSUE THREAD

**Issue by patflynn** [sigstore/sigstore-java#60]
Currently we have statically included the Rekor and Fulcio public keys into the library.  These keys should be updatable via TUF.

**Comment by patflynn** [comment]
Here is a list of follow on items that I need to do:

- [ ] Handle upcoming addition of PEM headers to role public keys. (ex)[https://github.com/sigstore/sigstore/compare/main...asraa:sigstore:test-migrate-root?expand=1]
- [ ] Implement local store interface to replace direct filesystem read/write
- [ ] Implement snapshot update
- [ ] Implement timestamp update
- [ ] Implement target updates
- [ ] add support for creating/managing map.json. I suspect we want to isolate our map.json repos from other clients.
- [ ] API for fetching TUF targets (rekor and fulcio public keys) with meta support for service url -> root mapping.  See client design (here)[https://docs.google.com/document/d/1QWBvpwYxOy9njAmd8vpizNQpPti9rd5ugVhji0r3T4c/edit]

Obviously as we add more resource types we need to refactor.  The good news is most of the weirdness in the parsing and verification has been tackled so the rest of the resources should be pretty quick. (famous last words).

**Comment by vlsi** [comment]
The question is how the default caching should work.
It would be weird if every signing would require TUF update.
On the other hand, if we claim `$HOME/.sigstore-java/caches/tuf`, then we would need to plan for concurrent access (e.g. multiple `sigstore-java` trying to update TUF concurrently).
On the other hand, it might be fun to have cross-ecosystem TUF cache, so the cache folder could be like `.sigstore/caches/tuf`

**Comment by loosebazooka** [comment]
done!
