### ISSUE TITLE
Change Fulcio to call V2 API

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/sigstore-java#65]
**Description**

We'd like to deprecate the V1 API, so we should switch the call to `api/v1/signingCert` to `api/v2/signingCert`. You can optionally switch to calls over gRPC too, but if you want to not pull in gRPC, HTTP still works.

cc @loosebazooka

**Comment by loosebazooka** [comment]
Nice

**Comment by haydentherapper** [comment]
Actually, didn’t realize you had already created a GRPC client. That is sufficient since that uses the v2 API. When would you be able to switch over to that as the default?

**Comment by jvanzyl** [comment]
I have a branch where I've flipped over to using this client so I'll try to get a PR up for that this weekend for @loosebazooka to take a look at.
