### ISSUE TITLE
Verify log checkpoint in addition to inclusion proof

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/sigstore-java#654]
**Description**

Currently, I believe that when the inclusion proof is verified, the [checkpoint](https://github.com/sigstore/protobuf-specs/blob/main/protos/sigstore_rekor.proto#L66) is not. Verifying the checkpoint is important since it ties the inclusion proof to the log, since the checkpoint is signed by the log. Without the checkpoint, you're verifying against an untrusted root hash with no link back to the log.

The Rekor public key, the same key used for verifying the SET, should be used to verify the checkpoint.

**Comment by loosebazooka** [comment]
fixed by #660
