### ISSUE TITLE
Support staging conformance tests

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-java#659]
sigstore-conformance 0.11 supports testing against staging infrastructure. This requires two things:
* Support the optional  `--staging` in all commands Sigstore-Java CLI, see [CLI protocol](https://github.com/sigstore/sigstore-conformance/blob/main/docs/cli_protocol.md)
* Add the extra call in conformance.yml, [README](https://github.com/sigstore/sigstore-conformance?tab=readme-ov-file#usage)

**Comment by loosebazooka** [comment]
done in #684
