### ISSUE TITLE
github release text has a broken url 

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-java#703]
release text looks like this:
> See [CHANGELOG.md](https://github.com//blob/main/CHANGELOG.md) for more details.

see e.g. https://github.com/sigstore/sigstore-java/releases/tag/v0.8.0

the changelog link is broken, probably because `${{ vars.GITHUB_REPOSITORY }}` in the workflow should be `${{ env.GITHUB_REPOSITORY }}`.

**Comment by loosebazooka** [comment]
hah. Thanks!
