### ISSUE TITLE
Publish cosign binaries to Sonatype OSSRH

### ISSUE THREAD

**Issue by vlsi** [sigstore/sigstore-java#74]
**Description**

I suggest adding a module to publish cosign binaries to Central.
That would enable consumers to download the needed binaries and execute `cosign` CLI.

See how protobuf plugin locates `protoc` binary: https://github.com/google/protobuf-gradle-plugin#locate-external-executables

An alternative option is to add publishing to `cosign` project itself.

**Comment by loosebazooka** [comment]
> An alternative option is to add publishing to cosign project itself.

I think this makes the most sense. I wonder if we can write the action here and execute on cosign releases?

**Comment by vlsi** [comment]
I have not explored how cosign is released, however, I just assumed that publishing cosign-as-jar would be easier from Gradle-based project (it could include Gradle Metadata for easier usage by consumers), and adding Gradle build to cosign might sound strange

**Comment by loosebazooka** [comment]
Yeah I don't mind doing it here if we can trigger by watching for new "releases" from cosign

**Comment by vlsi** [comment]
I guess it implies the current project should becomes multi-module one

**Comment by loosebazooka** [comment]
It could also just be multiple projects (or a new repo)

**Comment by vlsi** [comment]
I'm inclined that co-locating into a single repo might be easier to manage.

For instance, what if people want to have rekor-api and fulcio-api as separate dependencies?
What if they want cosign-binary-wrapped-as-java-api as yet another dependency?
It looks like having a single repo makes it easier to slice the module, and it would probably reduce the buildscript churn.

Frankly speaking, I think it might be fine to have both low-level Java libraries, Gradle, and maybe even Maven plugins within a single repository.

**Comment by vlsi** [comment]
It turns out `cosign` binaries are like 80-140 MiB, so I'm not sure we want to duplicate those releases to Central.
We might want to wait on the outcome of https://github.com/sigstore/cosign/issues/1462 first.

https://github.com/sigstore/cosign/releases/tag/v1.12.0

```
88.5 MB cosign-darwin-amd64
82.1 MB cosign-linux-arm64
144 MB cosign-windows-amd64.exe
```

**Comment by loosebazooka** [comment]
probably not doing this in the near future
