### ISSUE TITLE
Make KeylessSigningResult.disgest a wrapper class over algorithm+digest

### ISSUE THREAD

**Issue by vlsi** [sigstore/sigstore-java#85]
**Description**

Is `KeylessSigningResult` to be `sha256` always?

E.g. https://docs.google.com/document/d/1gucjOA_bGyRjK6TeaOI-X5GIUv8WsPzeMDMkq25Kv4Y/edit# consider having "algorithm" as an explicit field.

**Comment by loosebazooka** [comment]
This is handled by the messageDigest.HashAlgorithm field
