### ISSUE TITLE
Consider byte[] for digests and "byte64" data

### ISSUE THREAD

**Issue by vlsi** [sigstore/sigstore-java#86]
**Description**

The following would probably be better as `byte[]`:

```java
KeylessSigningResult {
  String getDigest();
```

```java
dev.sigstore.rekor.client.RekorEntry.InclusionProof {
List<String> getHashes();
```

**Comment by loosebazooka** [comment]
This is direct from the json, but I can add derived methods that provide this in more palatable types (`getDigestBytes()` and `getHashesBytes()`) and maybe this will all just kind of go away if rekor adopts the grpc based communication
