### ISSUE TITLE
Add test signing/verification interop tests with cosign CLI

### ISSUE THREAD

**Issue by patflynn** [sigstore/sigstore-java#97]
There's enough room for error in the production, canonicalization, and signing of sigstore data that testing against the signatures we produce or test data is not enough to ensure compatibility with the rest of sigstore tools (e.g. cosign).  We should have tests that ensure our verification and signing flows are interoperable with the cosign CLI.

**Comment by loosebazooka** [comment]
should be handled by sigstore-conformance
