### ISSUE TITLE
GitHub Actions OIDC test fails for pull requests from different repositories

### ISSUE THREAD

**Issue by vlsi** [sigstore/sigstore-java#99]
**Description**

The metadata token has `read` only permissions for PRs, so OIDC test fails:
https://github.com/sigstore/sigstore-java/runs/8153342788?check_suite_focus=true#step:1:17

I think OIDC tests should be skipped for PRs (or for PRs from different repos).
An alternative option is to skip OIDC tests if {{ACTIONS_ID_TOKEN...}} env variable exists

See failure for https://github.com/sigstore/sigstore-java/pull/98

**Version**

0eef92507f639f6d620ccfdcbf764a41ba9f6faf

**Comment by loosebazooka** [comment]
fixed by #114 but we still need to add it to the release script.

**Comment by vlsi** [comment]
PR builds succeed, so closing the issue
